branch-defaults:
  default:
    environment: phi-udagram-env
    group_suffix: null
environment-defaults:
  Phidt1udagram-env:
    branch: null
    repository: null
global:
  application_name: phi-udagram
  branch: null
  default_ec2_keyname: vockey
  default_platform: Node.js 18
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
